### ISSUE TITLE
Allow background color setting on side text and footer text

### ISSUE THREAD

**Issue by Beexx** [pytition/Pytition#172] opened 2019-11-02 15:11 UTC
Hello,

I haven't found any way to customize the background color of the side text and the footer text (currently dark grey). Currently you need to write text in white or light color to make it visible on this dark background.

It would be nice it this option was proposed, or if by default the text color would be white in these areas.

Also, not sure if this happens only to me, but the "Submit" button appears half hidden. See the attached screen shot. I'm using Firefox.

Thanks !

![screen2](https://user-images.githubusercontent.com/50069390/68072916-43209100-fd8b-11e9-9150-cfb52e85d7c8.jpg)

**Comment by fallen** [comment] 2019-11-04 12:38
I'm trying to keep a balance between what is "static" and what is "configurable" in the petition page template.
The balance is hard to find as everybody has different needs.

One way I see to provide more flexibility will be to implement: https://github.com/pytition/Pytition/issues/36

So that, if you really need a very custom design, you will be able to just add a new "template" and select it for your petition.
Kind of like WordPress Themes.

For the sign button issue, isn't the page scrollable? If not this is a bug!

**Comment by Beexx** [comment] 2019-11-04 14:24
Thanks, and yes, #36 would be great to solve this. 

For the sign button, no, the page is not scrollable when the petition text is smaller than the side text on the right. Do you want me to open a bug ?

**Comment by fallen** [comment] 2019-11-04 14:30
Ah yes this is a bug! I'm pretty sure this bug already existed and was fixed...
Sad it happened again!

**Comment by fallen** [comment] 2019-12-14 20:58
I'll close this one, as it's kind of a duplicate of #36
I cannot extend the configurability of the page to infinity, I don't think the user experience will be good in this case.
But with #36 you will surely be able to do what you want!

**Closed by fallen** 2019-12-14 20:58 UTC
Labels: enhancement
